name: Build and Cache ARM64 QEMU

on: [push, pull_request]  # 触发条件，可以是push或pull_request

jobs:
  build-and-cache-qemu:
    runs-on: ubuntu-latest  # 使用Ubuntu的最新版本作为运行器
    steps:
    
    - name: Install dependencies
      run: |
        git clone https://github.com/0zjn0123/qemu
        sudo apt-get install p7zip-full meson ninja-build
        cd qemu
        ls
        pwd
        ls -a -l
        
        sudo apt-get update
        sudo apt-get install sphinx
        sudo apt-get install -y git build-essential libglib2.0-dev pkg-config zlib1g-dev libpixman-1-dev git libfdt-dev libprotobuf-c-dev protobuf-c-compiler libxml2-utils libnuma-dev python3 python3-pip python3-venv

    - name: Install cross-compiler
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Install LLVM and Clang for AArch64
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "12.0.0"  # 您可以指定需要的版本
        arch: arm64  # 指定架构为arm64
    - name: Set environment variables for clang aarch64
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
    - name: Configure QEMU
      run: |
        cd qemu
        sudo apt-get install libepoxy-dev
        sudo apt-get install libgtk-3-dev
        pip install sphinx_rtd_theme
        #wget https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang+llvm-16.0.6-aarch64-linux-gnu.tar.xz
        #tar -xvf gcc-linaro-6.4.1-2017.11-x86_64_aarch64-linux-gnu.tar -C /usr/local/toolchain/
        #export PATH=$PATH:/usr/local/toolchain/gcc-linaro-6.4.1-2017.11-x86_64_aarch64-linux-gnu/bin
        
        
        ./configure --enable-kvm --enable-pixman --enable-opengl --enable-gtk  --enable-vnc --enable-guest-agent --cc=$CC --cxx=$CXX \
        --enable-cfi --enable-cfi-debug --enable-debug --enable-tcg --enable-plugins CFLAGS=-O2 CFLAGS=-g
      env:
        CROSS_COMPILE: aarch64-linux-gnu-

    - name: Build QEMU
      run: |
        cd qemu
        make -j$(nproc)
