name: Build and Cache ARM64 QEMU

on: [push, pull_request]  # 触发条件，可以是push或pull_request

jobs:
  build-and-cache-qemu:
    runs-on: ubuntu-latest  # 使用Ubuntu的最新版本作为运行器
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        repository: qemu/qemu
        path: qemu
        submodules: recursive

    - name: Cache QEMU
      uses: actions/cache@v4.2.0
      with:
        path: ./qemu
        key: ${{ runner.os }}-qemu-cache-${{ hashFiles('qemu/**') }}
        restore-keys: |
          ${{ runner.os }}-qemu-cache-
        save-always: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install ninja-build spice spice-protocol
        sudo apt-get install -y git build-essential libglib2.0-dev pkg-config zlib1g-dev libpixman-1-dev git libfdt-dev libprotobuf-c-dev protobuf-c-compiler libxml2-utils libnuma-dev

    - name: Install cross-compiler
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Configure QEMU
      run: |
        cd qemu
        ./configure --enable-kvm --enable-spice --enable-spice-protocol --enable-pixman --enable-opengl --enable-gtk  --enable-vnc --enable-guest-agent --cc=clang --cxx=clang++ --enable-cfi --enable-cfi-debug --enable-debug --enable-tcg --enable-plugins CFLAGS=-O2 CFLAGS=-g
      env:
        CROSS_COMPILE: aarch64-linux-gnu-

    - name: Build QEMU
      run: |
        cd qemu
        make -j$(nproc)
